version: "3.9"

services:
  app-blue:
    build:
      context: ./PWA-server
      dockerfile: Dockerfile
    container_name: vps-g-app-blue
    restart: always
    environment:
      - DATABASE_URL
      - K6_CLOUD_TOKEN
    expose:
      - "3001"
    networks:
      - appnet

  app-green:
    build:
      context: ./PWA-server
      dockerfile: Dockerfile
    container_name: vps-g-app-green
    restart: always
    environment:
      - DATABASE_URL
      - K6_CLOUD_TOKEN
    expose:
      - "3001"
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: vps-g-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/active.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-blue
      - app-green
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
