version: "3.9"

services:
  app:
    image: ghcr.io/doloressalinas/vps-g:latest
    container_name: vps-g-app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env   # Apunta a tu archivo local .env (solo en desarrollo)
    # Alternativamente, puedes definir variables expl√≠citas:
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - K6_CLOUD_TOKEN=${K6_CLOUD_TOKEN}

volumes:
  # Si necesitas persistencia de datos para la app, puedes agregar un volumen
  app_data:
