version: "3.9"

services:
  # Servicio que simula el entorno Blue
  app-blue:
    build:
      context: ./PWA-server
      dockerfile: Dockerfile
    container_name: vps-g-app-blue
    restart: always
    environment:
      # Las variables de entorno definidas
      - DATABASE_URL
      - K6_CLOUD_TOKEN
      - APP_COLOR=blue # Variable para diferenciar el entorno
    # Mapeo de puertos para el slot Blue
    # HOST_PORT:CONTAINER_PORT
    # El script de shell usa 3000 para Blue.
    ports:
      - "3000:3000"
    networks:
      - appnet

  # Servicio que simula el entorno Green
  app-green:
    build:
      context: ./PWA-server
      dockerfile: Dockerfile
    container_name: vps-g-app-green
    restart: always
    environment:
      # Las variables de entorno definidas
      - DATABASE_URL
      - K6_CLOUD_TOKEN
      - APP_COLOR=green # Variable para diferenciar el entorno
    # Mapeo de puertos para el slot Green
    # HOST_PORT:CONTAINER_PORT
    # El script de shell usa 3001 para Green.
    ports:
      - "3001:3000"
      - "3002:3000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge